package com.blach.unilife.view.navigation

object Routes {
    const val HOME_SCREEN = "HOME"
    const val LOGIN_SCREEN = "LOGIN"
    const val REGISTER_SCREEN = "REGISTER"
    const val CALENDAR_SCREEN = "CALENDAR"
    const val NEW_CALENDAR_EVENT_SCREEN = "NEW_CALENDAR_EVENT"
    const val NOTES_SCREEN = "NOTES"
    const val SINGLE_NOTE_SCREEN = "SINGLE_NOTE"
    const val TODO_SCREEN = "TODO"
    const val TODO_DONE_SCREEN = "TODO_DONE"
    const val TODO_TABS_SCREEN = "TODO_TABS"
    const val EXPENSE_TRACKER_SCREEN = "EXPENSE_TRACKER"
    const val NEW_EXPENSE_SCREEN = "NEW_EXPENSE"
    const val ALL_EXPENSES_TAB = "ALL_EXPENSES_TAB"
    const val HOME_AND_BILLS_TAB = "HOME_AND_BILLS_TAB"
    const val FOOD_TAB = "FOOD_TAB"
    const val HEALTH_AND_BEAUTY_TAB = "HEALTH_AND_BEAUTY_TAB"
    const val ENTERTAINMENT_AND_TRAVEL_TAB = "ENTERTAINMENT_AND_TRAVEL_TAB"
    const val CLOTHES_AND_ACCESSORIES_TAB = "CLOTHES_AND_ACCESSORIES_TAB"
    const val EDUCATION_TAB = "EDUCATION_TAB"
    const val TRANSPORT_TAB = "TRANSPORT_TAB"
    const val OTHER_TAB = "OTHER_TAB"

}